apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: metrics-server
    helm:
      values: |
        apiService:
          create: True
          insecureSkipTLSVerify: True
          extraArgs:
            - --kubelet-insecure-tls=true
            - --kubelet-preferred-address-types=InternalIP
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 0.6.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
