argo-cd:
  dex:
    enabled: false
  server:
    ingress:
      enabled: True
      hosts:
        - argo-cd.minikube1.marmite.zerotier.azulinho.com
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
